version: '4'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./Airflow/jobs:/opt/bitnami/spark/jobs
  networks:
    - subash-networks

x-airflow-common: &airflow-common
  build:
    context: ./Airflow/
    dockerfile: Dockerfile
  env_file:
    - ./Airflow/airflow.env
  volumes:
    - ./Airflow/jobs:/opt/airflow/jobs
    - ./Airflow/dags:/opt/airflow/dags
    - ./Airflow/logs:/opt/airflow/logs
    - ./Airflow/shared_jobs:/opt/shared_jobs
    - ./Airflow/Data:/opt/Data
    - ./Flask-app/models:/app/models
  depends_on:
    - postgres
  networks:
    - subash-networks

services:
  flask-app:
    build:
      context: ./Flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Airflow/Data:/opt/Data
      - ./Flask-app/static:/app/static
      - ./Flask-app/templates:/app/templates
      - ./Flask-app/models:/app/models
      - ./Flask-app/Neural_Network:/app/Neural_Network
    depends_on:
      - spark-master
      - webserver
    networks:
      - subash-networks


  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - subash-networks

  webserver:
    <<: *airflow-common
    command: webserver
    environment:
      - PYTHONPATH=/opt/airflow/jobs
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    environment:
      - PYTHONPATH=/opt/airflow/jobs
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Subash --lastname Rokka --role Admin --email airscholar@gmail.com --password admin && airflow scheduler"

networks:
  subash-networks:
